# Generated by Django 3.0.4 on 2020-04-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='referral_code',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
