# Generated by Django 3.0.4 on 2020-04-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200409_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='location',
        ),
    ]
