# Generated by Django 3.0.4 on 2020-04-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20200416_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
    ]
