# Generated by Django 3.0.4 on 2020-04-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_users_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='logo',
        ),
        migrations.AddField(
            model_name='users',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='userlogo/'),
        ),
    ]
