# Generated by Django 3.0.4 on 2020-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20200518_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(default='0000', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
