# Generated by Django 3.0.4 on 2020-06-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20200623_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='code',
            field=models.CharField(default='0000', max_length=10, null=True),
        ),
    ]
